"""Add AI provider management fields

Revision ID: 3f09ed5cf416
Revises: d0326732293a
Create Date: 2025-09-01 19:00:35.779094

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "3f09ed5cf416"
down_revision: Union[str, None] = "d0326732293a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "transformations", sa.Column("input_tokens", sa.Integer(), nullable=True)
    )
    op.add_column(
        "transformations", sa.Column("output_tokens", sa.Integer(), nullable=True)
    )
    op.add_column("transformations", sa.Column("ai_cost", sa.Float(), nullable=True))
    op.add_column(
        "transformations",
        sa.Column(
            "ai_response_metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
    )
    # Skip the index recreation - it's causing issues and not related to our AI provider changes
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("transformations", "ai_response_metadata")
    op.drop_column("transformations", "ai_cost")
    op.drop_column("transformations", "output_tokens")
    op.drop_column("transformations", "input_tokens")
    # Skip the index recreation - it's causing issues and not related to our AI provider changes
    # ### end Alembic commands ###
