"""add_task_id_to_transformations

Revision ID: d0326732293a
Revises: 6295f93177b8
Create Date: 2025-08-31 17:31:46.267691

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "d0326732293a"
down_revision: Union[str, None] = "6295f93177b8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "transformations", sa.Column("task_id", sa.String(length=255), nullable=True)
    )
    op.add_column(
        "transformations", sa.Column("ai_model", sa.String(length=100), nullable=True)
    )
    op.alter_column(
        "users",
        "role",
        existing_type=postgresql.ENUM(
            "OWNER", "ADMIN", "MEMBER", "VIEWER", name="userrole"
        ),
        nullable=False,
        existing_server_default=sa.text("'MEMBER'::userrole"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "role",
        existing_type=postgresql.ENUM(
            "OWNER", "ADMIN", "MEMBER", "VIEWER", name="userrole"
        ),
        nullable=True,
        existing_server_default=sa.text("'MEMBER'::userrole"),
    )
    op.drop_column("transformations", "ai_model")
    op.drop_column("transformations", "task_id")
    # ### end Alembic commands ###
